repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.7
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]

      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/dhruvmanila/remove-print-statements
    rev: v0.5.2
    hooks:
      - id: remove-print-statements
        args: [--verbose]
