name: Lint

on:
  pull_request:
  push:
    branches:
      - v2_main

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
        with:
          src: "./src/thoughtspot_tml"
